CREATE DATABASE MyDB;
GO

USE MyDB;
GO

CREATE TABLE COURSES (
    COURSE_ID INT PRIMARY KEY,
    NAMECOURSE VARCHAR(100),
    DESCRIPTION VARCHAR(100)
);
GO

CREATE TABLE GROUPS (
    GROUP_ID INT PRIMARY KEY,
    COURSE_ID INT,
    NAMEGROUP VARCHAR(100),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);
GO

CREATE TABLE STUDENTS (
    STUDENT_ID INT PRIMARY KEY,
    GROUP_ID INT,
    FIRST_NAME VARCHAR(60),
    LAST_NAME VARCHAR(60),
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(GROUP_ID)
);
GO